/*
Package pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package exceptions

import (
    "fmt"
    "github.com/apimatic/go-core-runtime/apiError"
)

// Api Error Exception
type Error struct {
    apiError.ApiError
    Message           *string                `json:"message"`
    Errors            map[string]interface{} `json:"errors"`
    Request           map[string]interface{} `json:"request"`
}

// Constructor for Error.
func NewError(
    statusCode int,
    body string) *Error {
    return &Error{
    	ApiError: apiError.ApiError{
    		StatusCode: statusCode,
    		Body:       body,
    	},
    }
}

// Implementing the Error method for the error interface.
func (e *Error) Error() string {
    return fmt.Sprintf("Error occured %v", e.Body)
}
