/*
Package pagarmeapisdk

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
*/
package data

// Response object for listing invoices
type ListInvoicesResponse struct {
    Data   *[]GetInvoiceResponse `json:"data"`
    Paging *PagingResponse       `json:"paging"`
}
